<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.10.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.14" />
	<PackageReference Include="Npgsql" Version="10.0.2" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\User.Application\User.Application.csproj" />
    <ProjectReference Include="..\User.Domain\User.Domain.csproj" />
  </ItemGroup>

</Project>
